version: '3'

services:
  master:
    build: .
    command: master
    tty: true
    ports:
      - "60000"
    volumes:
      - "./test/:/jmeter/sample/"
    networks:
      - jmeter-network
  server:
    image: pedrocesarti/jmeter-docker:latest
    command: server
    tty: true
    ports:
      - "50000"
      - "1099"
    networks:
      - jmeter-network
    depends_on:
      - master

networks:
  jmeter-network:
